CCPP SciDoc v7.0.0: module_sf_ruclsm::sfctmp
sfctmp()
subroutine module_sf_ruclsm::sfctmp (logical, intent(in) debug_print, real (kind_phys), intent(in) delt, integer, intent(in) ktau, real (kind_phys), intent(in) conflx, integer, intent(in) i, integer, intent(in) j, real (kind_phys), intent(in) xlat, real (kind_phys), intent(in) xlon, real (kind_phys), intent(in) testptlat, real (kind_phys), intent(in) testptlon, integer, intent(in) nzs, integer, intent(in) nddzs, integer, intent(in) nroot, real (kind_phys), intent(in) meltfactor, integer, intent(in) isncond_opt, integer, intent(in) isncovr_opt, integer, intent(inout) iland, integer, intent(inout) isoil, integer, intent(in) ivgtyp, integer, intent(in) isltyp, real (kind_phys) prcpms, real (kind_phys) newsnms, real (kind_phys), intent(inout) snwe, real (kind_phys), intent(inout) snhei, real (kind_phys), intent(inout) snowfrac, logical, intent(in) exticeden, real (kind_phys), intent(inout) rhosn, real (kind_phys), intent(in) rhonewsn_ex, real (kind_phys), intent(inout) rhonewsn, real (kind_phys), intent(inout) rhosnfall, real (kind_phys), intent(inout) snowrat, real (kind_phys), intent(inout) grauprat, real (kind_phys), intent(inout) icerat, real (kind_phys), intent(inout) curat, real (kind_phys), intent(in) patm, real (kind_phys), intent(in) tabs, real (kind_phys), intent(in) qvatm, real (kind_phys), intent(in) qcatm, real (kind_phys), intent(in) rho, real (kind_phys), intent(in) glw, real (kind_phys), intent(in) gswdn, real (kind_phys), intent(in) gsw, real (kind_phys), intent(inout) emiss, real (kind_phys), intent(inout) emisbck, real (kind_phys), intent(in) msnf, real (kind_phys), intent(in) facsnf, real (kind_phys), intent(in) qkms, real (kind_phys), intent(in) tkms, real (kind_phys), intent(in) pc, real (kind_phys), intent(inout) mavail, real (kind_phys), intent(inout) cst, real (kind_phys), intent(in) vegfra, real (kind_phys), intent(inout) alb, real (kind_phys), intent(inout) znt, real (kind_phys), intent(inout) alb_snow, real (kind_phys), intent(in) alb_snow_free, real (kind_phys), intent(in) lai, real (kind_phys), intent(in) hgt, real (kind_phys), intent(in) stdev, logical, intent(in) myj, real (kind_phys), intent(in) seaice, integer, intent(in) isice, logical, intent(in) add_fire_heat_flux, real (kind_phys), intent(in) fire_heat_flux, real (kind_phys) qwrtz, real (kind_phys) rhocs, real (kind_phys) dqm, real (kind_phys) qmin, real (kind_phys) ref, real (kind_phys) wilt, real (kind_phys) psis, real (kind_phys) bclh, real (kind_phys) ksat, real (kind_phys) sat, real (kind_phys), intent(in) cn, real (kind_phys), dimension(1:nzs), intent(in) zsmain, real (kind_phys), dimension(1:nzs), intent(in) zshalf, real (kind_phys), dimension(1:nddzs), intent(in) dtdzs, real (kind_phys), dimension(1:nzs), intent(in) dtdzs2, real (kind_phys), dimension(1:5001), intent(in) tbq, real (kind_phys), intent(in) cp, real (kind_phys), intent(in) rovcp, real (kind_phys), intent(in) g0, real (kind_phys), intent(in) lv, real (kind_phys), intent(in) stbolt, real (kind_phys), intent(in) cw, real (kind_phys), intent(in) c1sn, real (kind_phys), intent(in) c2sn, real (kind_phys), intent(in) kqwrtz, real (kind_phys), intent(in) kice, real (kind_phys), intent(in) kwt, real (kind_phys), intent(inout) snweprint, real (kind_phys), intent(inout) snheiprint, real (kind_phys), intent(inout) rsm, real (kind_phys), dimension(1:nzs), intent(inout) soilm1d, real (kind_phys), dimension(1:nzs), intent(inout) ts1d, real (kind_phys), dimension(1:nzs), intent(inout) smfrkeep, real (kind_phys), dimension(1:nzs), intent(inout) keepfr, real (kind_phys), intent(inout) soilt, real (kind_phys), intent(inout) soilt1, real (kind_phys), intent(inout) tsnav, real (kind_phys), intent(inout) dew, real (kind_phys), intent(inout) qvg, real (kind_phys), intent(inout) qsg, real (kind_phys), intent(inout) qcg, real (kind_phys), intent(inout) smelt, real (kind_phys), intent(inout) snoh, real (kind_phys), intent(inout) snflx, real (kind_phys), intent(inout) snom, real (kind_phys), intent(inout) snowfallac, real (kind_phys), intent(inout) acsnow, real (kind_phys), intent(inout) edir1, real (kind_phys), intent(inout) ec1, real (kind_phys), intent(inout) ett1, real (kind_phys), intent(inout) eeta, real (kind_phys), intent(inout) qfx, real (kind_phys), intent(inout) hfx, real (kind_phys), intent(inout) s, real (kind_phys), intent(inout) sublim, real (kind_phys), intent(inout) evapl, real (kind_phys), intent(inout) prcpl, real (kind_phys), intent(inout) fltot, real (kind_phys), intent(inout) runoff1, real (kind_phys), intent(inout) runoff2, real (kind_phys), dimension(1:nzs), intent(inout) soilice, real (kind_phys), dimension(1:nzs), intent(inout) soiliqw, real (kind_phys), intent(inout) infiltr, real (kind_phys), intent(inout) smf) private
It computes density of frozen precipitation from empirical dependence on temperature at the first atmospheric level.
Computes amount of liquid and frozen precipitation intercepted by the vegetation canopy.
In there is snow on the ground, the snow fraction is below 0.75, the snow "mosaic" approach is turned on.
Updates emissivity and albedo for patch snow.
Definition at line 1211 of file module_sf_ruclsm.F90.
References sice(), snowseaice(), snowsoil(), and soil().
Referenced by lsm_ruc::lsm_ruc_run(), and lsmruc().