CCPP SciDoc v7.0.0: module_mp_thompson::thompson_init
thompson_init() [2/2]
subroutine module_mp_thompson::thompson_init (logical, intent(in) is_aerosol_aware_in, logical, intent(in) merra2_aerosol_aware_in, type(mpi_comm), intent(in) mpicomm, integer, intent(in) mpirank, integer, intent(in) mpiroot, integer, intent(in) threads, character(len=*), intent(inout) errmsg, integer, intent(inout) errflg)
thompson_init General Algorithm
Allocate space for lookup tables (J. Michalakes 2009Jun08).
From Martin et al. (1994), assign gamma shape parameter mu for cloud drops according to general dispersion characteristics (disp=~0.25 for maritime and 0.45 for continental)
Compute Schmidt number to one-third used numerous times
Compute minimum ice diam from mass, min snow/graupel mass from diam
Compute constants various exponents and gamma() associated with cloud, rain, snow, and graupel
Simplify various rate equations
Compute rain collecting cloud water and cloud ice
Compute graupel collecting cloud water
Compute snow collecting cloud water
Compute snow collecting cloud ice
Compute evaporation of rain; ignore depositional growth of rain
Compute sublimation/depositional growth of snow
Compute melting of snow
Compute sublimation/depositional growth of graupel
Compute melting of graupel
Compute constants for helping find lookup table indexes
Create bins of cloud water (from min diameter up to 100 microns)
Create bins of cloud ice (from min diameter up to 2x min snow size)
Create bins of rain (from min diameter up to 5 mm)
Create bins of snow (from min diameter up to 2 cm)
Create bins of graupel (from min diameter up to 5 cm)
Create bins of cloud droplet number concentration (1 to 3000 per cc)
Create lookup tables for most costly calculations
Call table_ccnact() to read a static file containing CCN activation of aerosols. The data were created from a parcel model by Feingold & Heymsfield with further changes by Eidhammer and Kriedenweis
Call table_efrw() and table_efsw() to creat collision efficiency table between rain/snow and cloud water
Call table_dropevap() to creat rain drop evaporation table
Call qi_aut_qs() to create conversion of some ice mass into snow category
Call radar_init() to initialize various constants for computing radar reflectivity
Call qr_acr_qg() to create rain collecting graupel & graupel collecting rain table
Call qr_acr_qs() to create rain collecting snow & snow collecting rain table
Call freezeh2o() to create cloud water and rain freezing (Bigg, 1953) table
Definition at line 445 of file module_mp_thompson.F90.
References freezeh2o(), qi_aut_qs(), qr_acr_qg(), qr_acr_qs(), table_ccnact(), table_dropevap(), table_efrw(), table_efsw(), and wgamma().
Referenced by mp_thompson::mp_thompson_init().