CCPP SciDoc v7.0.0: module_mp_nssl_2mom::nssl_2mom_driver
nssl_2mom_driver()
subroutine, public module_mp_nssl_2mom::nssl_2mom_driver (real, dimension(ims:ime, kms:kme, jms:jme), intent(inout) qv, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout) qc, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout) qr, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional qi, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout) qs, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout) qh, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional qhl, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional ccw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional crw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cci, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional csw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional chw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional chl, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cn, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional vhw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional vhl, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cna, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cni, logical, intent(in), optional f_cn, logical, intent(in), optional f_cna, logical, intent(in), optional f_cina, logical, intent(in), optional f_qc, logical, intent(in), optional f_qr, logical, intent(in), optional f_qi, logical, intent(in), optional f_qs, logical, intent(in), optional f_qh, logical, intent(in), optional f_qhl, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cn_nu, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cn_co, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cinp, logical, intent(in), optional f_cnnu, logical, intent(in), optional f_cnco, logical, intent(in), optional f_cinp, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cna_co, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cna_nu, logical, intent(in), optional f_cnaco, logical, intent(in), optional f_cnanu, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cnuf, logical, intent(in), optional f_cnuf, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional cn_ac, logical, intent(in), optional f_cnac, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional zrw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional zhw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional zhl, logical, intent(in), optional f_zrw, logical, intent(in), optional f_zhw, logical, intent(in), optional f_zhl, logical, intent(in), optional f_vhw, logical, intent(in), optional f_vhl, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional qsw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional qhw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional qhlw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional tt, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional th, real, dimension(ims:ime, kms:kme, jms:jme), intent(in) pii, real, dimension(ims:ime, kms:kme, jms:jme), intent(in) p, real, dimension(ims:ime, kms:kme, jms:jme), intent(in) w, real, dimension(ims:ime, kms:kme, jms:jme), intent(in) dn, real, dimension(ims:ime, kms:kme, jms:jme), intent(in) dz, real, intent(in) dtp, integer, intent(in) itimestep, integer, intent(in), optional is_theta_or_temp, integer, intent(in), optional ntmul, integer, intent(in), optional ntcnt, logical, intent(in), optional lastloop, real, dimension(ims:ime, jms:jme) rainnc, real, dimension(ims:ime, jms:jme) rainncv, real, intent(in), optional dx, real, intent(in), optional dy, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional axtra, real, dimension(ims:ime, jms:jme), intent(inout), optional snownc, real, dimension(ims:ime, jms:jme), intent(inout), optional snowncv, real, dimension(ims:ime, jms:jme), intent(inout), optional grplnc, real, dimension(ims:ime, jms:jme), intent(inout), optional grplncv, real, dimension(ims:ime, jms:jme), intent(inout), optional sr, real, dimension(ims:ime, jms:jme), intent(inout), optional hailnc, real, dimension(ims:ime, jms:jme), intent(inout), optional hailncv, real, dimension(ims:ime, jms:jme), intent(inout), optional hail_maxk1, real, dimension(ims:ime, jms:jme), intent(inout), optional hail_max2d, integer, intent(in), optional nwp_diagnostics, real, dimension(ims:ime, kms:kme, jms:jme), intent(in), optional tkediss, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional re_cloud, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional re_ice, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional re_snow, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional re_rain, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional re_graup, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional re_hail, integer, intent(in), optional has_reqc, integer, intent(in), optional has_reqi, integer, intent(in), optional has_reqs, integer, intent(in), optional has_reqr, integer, intent(in), optional has_reqg, integer, intent(in), optional has_reqh, real, dimension(ims:ime, jms:jme), intent(out), optional rainncw2, real, dimension(ims:ime, jms:jme), intent(out), optional rainnci2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional dbz, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional vzf, real, dimension(ims:ime, jms:jme), intent(inout), optional compdbz, real, dimension(ims:ime, jms:jme), intent(inout), optional rscghis_2d, real, dimension(ims:ime, jms:jme), intent(inout), optional rscghis_2dp, real, dimension(ims:ime, jms:jme), intent(inout), optional rscghis_2dn, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional scr, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional scw, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional sci, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional scs, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional sch, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional schl, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional sctot, integer, intent(in), optional elec_physics, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional induc, real, dimension(ims:ime, kms:kme, jms:jme), intent(in), optional elecz, real, dimension(ims:ime, kms:kme, jms:jme, 2), intent(inout), optional scion, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional sciona, logical, intent(in), optional f_scion, logical, intent(in), optional f_sciona, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional noninduc, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional noninducp, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional noninducn, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional ssat3d, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional ssati, integer, intent(in), optional nssl_ssat_output, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional pcc2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional pre2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional depsubr, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional mnucf2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional melr2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional ctr2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional rim1_2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional rim2_2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional rim3_2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional nctr2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional nnuccd2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional nnucf2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional effc2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional effr2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional effi2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional effs2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional effg2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fc2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fr2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fi2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fs2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fg2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fnc2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fnr2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fni2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fns2, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional fng2, integer, intent(in), optional ipelectmp, integer, intent(in), optional isedonly_in, logical, intent(in), optional diagflag, integer, intent(in), optional ke_diag, character(len=*), intent(out) errmsg, integer, intent(out) errflg, logical, intent(in), optional nssl_progn, logical, intent(in), optional wetscav_on, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional rainprod, real, dimension(ims:ime, kms:kme, jms:jme), intent(inout), optional evapprod, integer, intent(in), optional cu_used, real, dimension(ims:ime, kms:kme, jms:jme), intent(in), optional qrcuten, real, dimension(ims:ime, kms:kme, jms:jme), intent(in), optional qscuten, real, dimension(ims:ime, kms:kme, jms:jme), intent(in), optional qicuten, real, dimension(ims:ime, kms:kme, jms:jme), intent(in), optional qccuten, integer, intent(in) ids, integer, intent(in) ide, integer, intent(in) jds, integer, intent(in) jde, integer, intent(in) kds, integer, intent(in) kde, integer, intent(in) ims, integer, intent(in) ime, integer, intent(in) jms, integer, intent(in) jme, integer, intent(in) kms, integer, intent(in) kme, integer, intent(in) its, integer, intent(in) ite, integer, intent(in) jts, integer, intent(in) jte, integer, intent(in) kts, integer, intent(in) kte)
Definition at line 2402 of file module_mp_nssl_2mom.F90.
References calc_eff_radius(), calcnfromcuten(), calcnfromq(), hailmaxd(), nssl_2mom_gs(), nucond(), radardd02(), and sediment1d().
Referenced by mp_nssl::mp_nssl_run().