CCPP SciDoc v7.0.0: rrtmg_sw::taumol
taumol()
subroutine rrtmg_sw::taumol (real (kind=kind_phys), dimension(nlay,maxgas), intent(in) colamt, real (kind=kind_phys), dimension(nlay), intent(in) colmol, real (kind=kind_phys), dimension(nlay), intent(in) fac00, real (kind=kind_phys), dimension(nlay), intent(in) fac01, real (kind=kind_phys), dimension(nlay), intent(in) fac10, real (kind=kind_phys), dimension(nlay), intent(in) fac11, integer, dimension(nlay), intent(in) jp, integer, dimension(nlay), intent(in) jt, integer, dimension(nlay), intent(in) jt1, integer, intent(in) laytrop, real (kind=kind_phys), dimension(nlay), intent(in) forfac, real (kind=kind_phys), dimension(nlay), intent(in) forfrac, integer, dimension(nlay), intent(in) indfor, real (kind=kind_phys), dimension(nlay), intent(in) selffac, real (kind=kind_phys), dimension(nlay), intent(in) selffrac, integer, dimension(nlay), intent(in) indself, integer, intent(in) nlay, real (kind=kind_phys), dimension(ngptsw), intent(out) sfluxzen, real (kind=kind_phys), dimension(nlay,ngptsw), intent(out) taug, real (kind=kind_phys), dimension(nlay,ngptsw), intent(out) taur) private
Parameters
colamt column amounts of absorbing gases the index are for h2o, co2, o3, n2o, ch4, and o2, respectively \((mol/cm^2)\)
colmol total column amount (dry air+water vapor)
fac00,fac01,fac10,fac11 for each layer, these are factors that are needed to compute the interpolation factors that multiply the appropriate reference k-values. a value of 0/1 for i,j indicates that the corresponding factor multiplies reference k-value for the lower/higher of the two appropriate temperatures, and altitudes, respectively.
jp the index of the lower (in altitude) of the two appropriate ref pressure levels needed for interpolation.
jt,jt1 the indices of the lower of the two approp ref temperatures needed for interpolation (for pressure levels jp and jp+1, respectively)
laytrop tropopause layer index
forfac scale factor needed to foreign-continuum.
forfrac factor needed for temperature interpolation
indfor index of the lower of the two appropriate reference temperatures needed for foreign-continuum interpolation
selffac scale factor needed to h2o self-continuum.
selffrac factor needed for temperature interpolation of reference h2o self-continuum data
indself index of the lower of the two appropriate reference temperatures needed for the self-continuum interpolation
nlay number of vertical layers
sfluxzen spectral distribution of incoming solar flux
taug spectral optical depth for gases
taur opt depth for rayleigh scattering
taumol General Algorithm
Call taumol## (##: 16-29) to calculate layer optical depth.
call taumol16()
call taumol17()
call taumol18()
call taumol19()
call taumol20()
call taumol21()
call taumol22()
call taumol23()
call taumol24()
call taumol25()
call taumol26()
call taumol27()
call taumol28()
call taumol29()
Definition at line 4096 of file radsw_main.F90.
References taumol16(), taumol17(), taumol18(), taumol19(), taumol20(), taumol21(), taumol22(), taumol23(), taumol24(), taumol25(), taumol26(), taumol27(), taumol28(), and taumol29().
Referenced by rrtmg_sw_run().