CCPP SciDoc v7.0.0: module_radiation_clouds::radiation_clouds_prop
radiation_clouds_prop()
subroutine, public module_radiation_clouds::radiation_clouds_prop (real (kind=kind_phys), dimension(:,:), intent(in) plyr, real (kind=kind_phys), dimension(:,:), intent(in) plvl, real (kind=kind_phys), dimension(:,:), intent(in) tlyr, real (kind=kind_phys), dimension(:,:), intent(in) tvly, real (kind=kind_phys), dimension(:,:), intent(in) qlyr, real (kind=kind_phys), dimension(:,:), intent(in) qstl, real (kind=kind_phys), dimension(:,:), intent(in) rhly, real (kind=kind_phys), dimension(:,:,:), intent(in) ccnd, integer, intent(in) ncndl, real (kind=kind_phys), dimension(:,:), intent(in) cnvw, real (kind=kind_phys), dimension(:,:), intent(in) cnvc, real (kind=kind_phys), dimension(:,:,:), intent(in) tracer1, real (kind=kind_phys), dimension(:), intent(in) xlat, real (kind=kind_phys), dimension(:), intent(in) xlon, real (kind=kind_phys), dimension(:), intent(in) slmsk, real (kind=kind_phys), dimension(:,:), intent(in) dz, real (kind=kind_phys), dimension(:,:), intent(in) delp, integer, intent(in) ix, integer, intent(in) lm, integer, intent(in) nlay, integer, intent(in) nlp1, real(kind=kind_phys), dimension(:,:) deltaq, real (kind=kind_phys), intent(in) sup, real (kind=kind_phys), intent(in) dcorr_con, integer, intent(in) me, integer, intent(in) icloud, integer, intent(in) kdt, integer, intent(in) ntrac, integer, intent(in) ntcw, integer, intent(in) ntiw, integer, intent(in) ntrw, integer, intent(in) ntsw, integer, intent(in) ntgl, integer, intent(in) ntclamt, integer, intent(in) imp_physics, imp_physics_nssl, imp_physics_fer_hires, imp_physics_gfdl, imp_physics_thompson, imp_physics_wsm6, imp_physics_tempo, imp_physics_zhao_carr, imp_physics_zhao_carr_pdf, imp_physics_mg, integer, intent(in) iovr, iovr_rand, iovr_maxrand, iovr_max, iovr_dcorr, iovr_exp, iovr_exprand, idcor, idcor_con, idcor_hogan, idcor_oreopoulos, logical, intent(in) lcrick, logical, intent(in) lcnorm, integer, intent(in) imfdeepcnv, integer, intent(in) imfdeepcnv_gf, integer, intent(in) imfdeepcnv_c3, logical, intent(in) do_mynnedmf, logical, intent(in) lgfdlmprad, logical, intent(in) xr_cnvcld, logical, intent(in) uni_cld, logical, intent(in) lmfshal, logical, intent(in) lmfdeep2, real (kind=kind_phys), dimension(:,:), intent(in) cldcov, real (kind=kind_phys), dimension(:,:), intent(in) clouds1, real (kind=kind_phys), dimension(:,:), intent(in) effrl, real (kind=kind_phys), dimension(:,:), intent(in) effri, real (kind=kind_phys), dimension(:,:), intent(in) effrr, real (kind=kind_phys), dimension(:,:), intent(in) effrs, logical, intent(in) effr_in, real(kind=kind_phys), dimension(:,:), intent(inout) effrl_inout, real(kind=kind_phys), dimension(:,:), intent(inout) effri_inout, real(kind=kind_phys), dimension(:,:), intent(inout) effrs_inout, real(kind=kind_phys), dimension(:), intent(inout) lwp_ex, real(kind=kind_phys), dimension(:), intent(inout) iwp_ex, real(kind=kind_phys), dimension(:), intent(inout) lwp_fc, real(kind=kind_phys), dimension(:), intent(inout) iwp_fc, real (kind=kind_phys), dimension(:,:), intent(in) dzlay, real(kind=kind_phys), dimension(:), intent(in) latdeg, real(kind=kind_phys), intent(in) julian, integer, intent(in) yearlen, real(kind=kind_phys), dimension(:), intent(in) gridkm, logical, intent(in) top_at_1, real (kind=kind_phys), dimension(:), intent(in) si, real (kind=kind_phys), intent(in) xr_con, real (kind=kind_phys), intent(in) xr_exp, real (kind=kind_phys), intent(in) con_ttp, real (kind=kind_phys), intent(in) con_pi, real (kind=kind_phys), intent(in) con_g, real (kind=kind_phys), intent(in) con_rd, real (kind=kind_phys), intent(in) con_thgni, real (kind=kind_phys), dimension(:,:), intent(out) cld_frac, real (kind=kind_phys), dimension(:,:), intent(out) cld_lwp, real (kind=kind_phys), dimension(:,:), intent(out) cld_reliq, real (kind=kind_phys), dimension(:,:), intent(out) cld_iwp, real (kind=kind_phys), dimension(:,:), intent(out) cld_reice, real (kind=kind_phys), dimension(:,:), intent(out) cld_rwp, real (kind=kind_phys), dimension(:,:), intent(out) cld_rerain, real (kind=kind_phys), dimension(:,:), intent(out) cld_swp, real (kind=kind_phys), dimension(:,:), intent(out) cld_resnow, real (kind=kind_phys), dimension(:,:), intent(out) clds, integer, dimension(:,:), intent(out) mtop, integer, dimension(:,:), intent(out) mbot, real (kind=kind_phys), dimension(:), intent(out) de_lgth, real (kind=kind_phys), dimension(:,:), intent(out) alpha)
General Algorithm
Compute SFC/low/middle/high cloud top pressure for each cloud domain for given latitude.
Call gethml() to compute low,mid,high,total, and boundary layer cloud fractions and clouds top/bottom layer indices for low, mid, and high clouds.
Definition at line 340 of file radiation_clouds.f.
References gethml(), nk_clds, progcld_fer_hires(), progcld_gfdl_lin(), progcld_thompson(), progcld_thompson_wsm6(), progcld_zhao_carr(), progcld_zhao_carr_pdf(), progclduni(), and ptopc.