CCPP SciDoc v7.0.0: energy
energy()
subroutine __module_sf_noahmplsm_f90__::energy (type (noahmp_parameters), intent(in) parameters, integer, intent(in) ice, integer, intent(in) vegtyp, integer, intent(in) ist, integer, intent(in) nsnow, integer, intent(in) nsoil, integer, intent(in) isnow, real (kind=kind_phys), intent(in) dt, real (kind=kind_phys), intent(in) rhoair, real (kind=kind_phys), intent(in) sfcprs, real (kind=kind_phys), intent(in) qair, real (kind=kind_phys), intent(in) sfctmp, real (kind=kind_phys), intent(in) thair, real (kind=kind_phys), intent(in) lwdn, real (kind=kind_phys), intent(in) uu, real (kind=kind_phys), intent(in) vv, real (kind=kind_phys), intent(in) zref, real (kind=kind_phys), intent(in) co2air, real (kind=kind_phys), intent(in) o2air, real (kind=kind_phys), dimension(1: 2), intent(in) solad, real (kind=kind_phys), dimension(1: 2), intent(in) solai, real (kind=kind_phys), intent(in) cosz, real (kind=kind_phys), intent(in) igs, real (kind=kind_phys), intent(in) eair, real (kind=kind_phys), intent(in) tbot, real (kind=kind_phys), dimension(-nsnow+1:nsoil), intent(in) zsnso, real (kind=kind_phys), dimension(1:nsoil), intent(in) zsoil, real (kind=kind_phys), intent(in) elai, real (kind=kind_phys), intent(in) esai, real (kind=kind_phys), intent(in) fwet, real (kind=kind_phys), intent(in) foln, real (kind=kind_phys), intent(in) fveg, real (kind=kind_phys), intent(in) shdfac, real (kind=kind_phys), intent(in) pahv, real (kind=kind_phys), intent(in) pahg, real (kind=kind_phys), intent(in) pahb, real (kind=kind_phys), intent(in) qsnow, real (kind=kind_phys), dimension(-nsnow+1:nsoil), intent(in) dzsnso, real (kind=kind_phys), intent(in) lat, real (kind=kind_phys), intent(in) canliq, real (kind=kind_phys), intent(in) canice, integer, intent(in) iloc, integer, intent(in) jloc, logical, intent(in) thsfc_loc, real (kind=kind_phys), intent(in) prslkix, real (kind=kind_phys), intent(in) prsik1x, real (kind=kind_phys), intent(in) prslk1x, real (kind=kind_phys), intent(in) garea1, real (kind=kind_phys), intent(in) pblhx, integer, intent(in) iz0tlnd, integer, intent(in) itime, integer, intent(in) psi_opt, real (kind=kind_phys), intent(in) ep_1, real (kind=kind_phys), intent(in) ep_2, real (kind=kind_phys), intent(in) epsm1, real (kind=kind_phys), intent(in) cp, real (kind=kind_phys), intent(out) z0wrf, real (kind=kind_phys), intent(out) z0hwrf, integer, dimension(-nsnow+1:nsoil), intent(out) imelt, real (kind=kind_phys), dimension(-nsnow+1: 0), intent(out) snicev, real (kind=kind_phys), dimension(-nsnow+1: 0), intent(out) snliqv, real (kind=kind_phys), dimension(-nsnow+1: 0), intent(out) epore, real (kind=kind_phys), intent(out) t2m, real (kind=kind_phys), intent(out) fsno, real (kind=kind_phys), intent(out) sav, real (kind=kind_phys), intent(out) sag, real (kind=kind_phys), intent(out) qmelt, real (kind=kind_phys), intent(out) fsa, real (kind=kind_phys), intent(out) fsr, real (kind=kind_phys), intent(out) taux, real (kind=kind_phys), intent(out) tauy, real (kind=kind_phys), intent(out) fira, real (kind=kind_phys), intent(out) fsh, real (kind=kind_phys), intent(out) fcev, real (kind=kind_phys), intent(out) fgev, real (kind=kind_phys), intent(out) fctr, real (kind=kind_phys), intent(out) trad, real (kind=kind_phys), intent(out) psn, real (kind=kind_phys), intent(out) apar, real (kind=kind_phys), intent(out) ssoil, real (kind=kind_phys), dimension(1:nsoil), intent(out) btrani, real (kind=kind_phys), intent(out) btran, real (kind=kind_phys), intent(out) ponding, real (kind=kind_phys), intent(out) ts, real (kind=kind_phys), intent(out) latheav, real (kind=kind_phys), intent(out) latheag, logical, intent(out) frozen_canopy, logical, intent(out) frozen_ground, real (kind=kind_phys), intent(inout) tv, real (kind=kind_phys), intent(inout) tg, real (kind=kind_phys), dimension(-nsnow+1:nsoil), intent(inout) stc, real (kind=kind_phys), intent(inout) snowh, real (kind=kind_phys), intent(inout) eah, real (kind=kind_phys), intent(inout) tah, real (kind=kind_phys), intent(inout) sneqvo, real (kind=kind_phys), intent(inout) sneqv, real (kind=kind_phys), dimension(1:nsoil), intent(inout) sh2o, real (kind=kind_phys), dimension(1:nsoil), intent(inout) smc, real (kind=kind_phys), dimension(-nsnow+1: 0), intent(inout) snice, real (kind=kind_phys), dimension(-nsnow+1: 0), intent(inout) snliq, real (kind=kind_phys), intent(inout) albold, real (kind=kind_phys), intent(inout) cm, real (kind=kind_phys), intent(inout) ch, real (kind=kind_phys), intent(in) dx, real (kind=kind_phys), intent(in) dz8w, real (kind=kind_phys), intent(in) q2, real (kind=kind_phys), intent(inout) ustarx, ifdef, ccpp) private
Parameters
[in] ice ice (ice = 1)
[in] vegtyp vegetation physiology type
[in] ist surface type: 1->soil; 2->lake
[in] nsnow maximum no. of snow layers
[in] nsoil number of soil layers
[in] isnow actual no. of snow layers
[in] dt time step [sec]
[in] qsnow snowfall on the ground (mm/s)
[in] rhoair density air (kg/m3)
[in] eair vapor pressure air (pa)
[in] sfcprs pressure (pa)
[in] prslkix in exner function
[in] prsik1x in exner function
[in] prslk1x in exner function
[in] pblhx pbl height
[in] qair specific humidity (kg/kg)
[in] sfctmp air temperature (k)
[in] thair potential temperature (k)
[in] lwdn downward longwave radiation (w/m2)
[in] uu wind speed in e-w dir (m/s)
[in] vv wind speed in n-s dir (m/s)
[in] solad incoming direct solar rad. (w/m2)
[in] solai incoming diffuse solar rad. (w/m2)
[in] cosz cosine solar zenith angle (0-1)
[in] elai lai adjusted for burying by snow
[in] esai lai adjusted for burying by snow
[in] fwet fraction of canopy that is wet [-]
[in] fveg greeness vegetation fraction (-)
[in] shdfac green vegetation fraction [0.0-1.0]
[in] lat latitude (radians)
[in] canliq canopy-intercepted liquid water (mm)
[in] canice canopy-intercepted ice mass (mm)
[in] foln foliage nitrogen (%)
[in] co2air atmospheric co2 concentration (pa)
[in] o2air atmospheric o2 concentration (pa)
[in] igs growing season index (0=off, 1=on)
[in] zref reference height (m)
[in] tbot bottom condition for soil temp. (k)
[in] zsnso layer-bottom depth from snow surf [m]
[in] zsoil layer-bottom depth from soil surf [m]
[in] dzsnso depth of snow & soil layer-bottom [m]
[in] pahv precipitation advected heat - vegetation net (w/m2)
[in] pahg precipitation advected heat - under canopy net (w/m2)
[in] pahb precipitation advected heat - bare ground net (w/m2)
[in] dx horisontal resolution
[in] dz8w thickness of lowest layer
[in] q2 mixing ratio (kg/kg)
[out] z0wrf combined z0 sent to coupled model
[out] z0hwrf combined z0h sent to coupled model
[out] imelt phase change index [1-melt; 2-freeze]
[out] snicev partial volume ice [m3/m3]
[out] snliqv partial volume liq. water [m3/m3]
[out] epore effective porosity [m3/m3]
[out] fsno snow cover fraction (-)
[out] qmelt snowmelt [mm/s]
[out] ponding pounding at ground [mm]
[out] sav solar rad. absorbed by veg. (w/m2)
[out] sag solar rad. absorbed by ground (w/m2)
[out] fsa tot. absorbed solar radiation (w/m2)
[out] fsr tot. reflected solar radiation (w/m2)
[out] taux wind stress: e-w (n/m2)
[out] tauy wind stress: n-s (n/m2)
[out] fira total net lw. rad (w/m2) [+ to atm]
[out] fsh total sensible heat (w/m2) [+ to atm]
[out] fcev canopy evaporation (w/m2) [+ to atm]
[out] fgev ground evaporation (w/m2) [+ to atm]
[out] fctr transpiration (w/m2) [+ to atm]
[out] trad radiative temperature (k)
[out] t2m 2 m height air temperature (k)
[out] psn total photosyn. (umolco2/m2/s) [+]
[out] apar total photosyn. active energy (w/m2)
[out] ssoil ground heat flux (w/m2) [+ to soil]
[out] btrani soil water transpiration factor (0-1)
[out] btran soil water transpiration factor (0-1)
[out] latheav latent heat vap./sublimation (j/kg)
[out] latheag latent heat vap./sublimation (j/kg)
[out] ts surface temperature (k)
[out] frozen_ground used to define latent heat pathway
[out] frozen_canopy used to define latent heat pathway
[in,out] tv vegetation temperature (k)
[in,out] tg ground temperature (k)
[in,out] stc snow/soil temperature [k]
[in,out] snowh snow height [m]
[in,out] sneqv snow mass (mm)
[in,out] sneqvo snow mass at last time step (mm)
[in,out] sh2o liquid soil moisture [m3/m3]
[in,out] smc soil moisture (ice + liq.) [m3/m3]
[in,out] snice snow ice mass (kg/m2)
[in,out] snliq snow liq mass (kg/m2)
[in,out] eah canopy air vapor pressure (pa)
[in,out] tah canopy air temperature (k)
[in,out] albold snow albedo at last time step(class type)
[in,out] cm momentum drag coefficient
[in,out] ch sensible heat exchange coefficient
[in,out] ustarx friction velocity
Definition at line 1672 of file module_sf_noahmplsm.F90.
References bare_flux(), phasechange(), radiation(), thermalz0(), thermoprop(), tsnosoi(), and vege_flux().
Referenced by noahmp_sflx(), samfdeepcnv::samfdeepcnv_run(), and samfshalcnv::samfshalcnv_run().