CCPP SciDoc v7.0.0: noahmp_sflx
noahmp_sflx()
subroutine __module_sf_noahmplsm_f90__::noahmp_sflx (type (noahmp_parameters), intent(in) parameters, integer, intent(in) iloc, integer, intent(in) jloc, real (kind=kind_phys), intent(in) lat, integer, intent(in) yearlen, real (kind=kind_phys), intent(in) julian, real (kind=kind_phys), intent(in) cosz, real (kind=kind_phys), intent(in) dt, real (kind=kind_phys), intent(in) dx, real (kind=kind_phys), intent(in) dz8w, integer, intent(in) nsoil, real (kind=kind_phys), dimension(1:nsoil), intent(in) zsoil, integer, intent(in) nsnow, real (kind=kind_phys), intent(in) shdfac, real (kind=kind_phys), intent(in) shdmax, integer, intent(in) vegtyp, integer, intent(in) ice, integer, intent(in) ist, integer, intent(in) croptype, real (kind=kind_phys), dimension(1:nsoil), intent(in) smceq, real (kind=kind_phys), intent(in) sfctmp, real (kind=kind_phys), intent(in) sfcprs, real (kind=kind_phys), intent(in) psfc, real (kind=kind_phys), intent(in) uu, real (kind=kind_phys), intent(in) vv, real (kind=kind_phys), intent(in) q2, real (kind=kind_phys), intent(in) garea1, real (kind=kind_phys), intent(in) qc, real (kind=kind_phys), intent(in) soldn, real (kind=kind_phys), intent(in) lwdn, logical, intent(in) thsfc_loc, real (kind=kind_phys), intent(in) prslkix, real (kind=kind_phys), intent(in) prsik1x, real (kind=kind_phys), intent(in) prslk1x, real (kind=kind_phys), intent(in) pblhx, integer, intent(in) iz0tlnd, integer, intent(in) itime, integer, intent(in) psi_opt, real (kind=kind_phys), intent(in) prcpconv, real (kind=kind_phys), intent(in) prcpnonc, real (kind=kind_phys), intent(in) prcpshcv, real (kind=kind_phys), intent(in) prcpsnow, real (kind=kind_phys), intent(in) prcpgrpl, real (kind=kind_phys), intent(in) prcphail, real (kind=kind_phys), intent(in) tbot, real (kind=kind_phys), intent(in) co2air, real (kind=kind_phys), intent(in) o2air, real (kind=kind_phys), intent(in) foln, real (kind=kind_phys), dimension(-nsnow+1: 0), intent(in) ficeold, real (kind=kind_phys), intent(inout) zlvl, real (kind=kind_phys), intent(in) ep_1, real (kind=kind_phys), intent(in) ep_2, real (kind=kind_phys), intent(in) epsm1, real (kind=kind_phys), intent(in) cp, real (kind=kind_phys), intent(inout) albold, real (kind=kind_phys), intent(inout) sneqvo, real (kind=kind_phys), dimension(-nsnow+1:nsoil), intent(inout) stc, real (kind=kind_phys), dimension(1:nsoil), intent(inout) sh2o, real (kind=kind_phys), dimension(1:nsoil), intent(inout) smc, real (kind=kind_phys), intent(inout) tah, real (kind=kind_phys), intent(inout) eah, real (kind=kind_phys), intent(inout) fwet, real (kind=kind_phys), intent(inout) canliq, real (kind=kind_phys), intent(inout) canice, real (kind=kind_phys), intent(inout) tv, real (kind=kind_phys), intent(inout) tg, real (kind=kind_phys), intent(inout) qsfc, real (kind=kind_phys), intent(inout) qsnow, real (kind=kind_phys), intent(inout) qrain, integer, intent(inout) isnow, real (kind=kind_phys), dimension(-nsnow+1:nsoil), intent(inout) zsnso, real (kind=kind_phys), intent(inout) snowh, real (kind=kind_phys), intent(inout) sneqv, real (kind=kind_phys), dimension(-nsnow+1: 0), intent(inout) snice, real (kind=kind_phys), dimension(-nsnow+1: 0), intent(inout) snliq, real (kind=kind_phys), intent(inout) zwt, real (kind=kind_phys), intent(inout) wa, real (kind=kind_phys), intent(inout) wt, real (kind=kind_phys), intent(inout) wslake, real (kind=kind_phys), intent(inout) lfmass, real (kind=kind_phys), intent(inout) rtmass, real (kind=kind_phys), intent(inout) stmass, real (kind=kind_phys), intent(inout) wood, real (kind=kind_phys), intent(inout) stblcp, real (kind=kind_phys), intent(inout) fastcp, real (kind=kind_phys), intent(inout) lai, real (kind=kind_phys), intent(inout) sai, real (kind=kind_phys), intent(inout) cm, real (kind=kind_phys), intent(inout) ch, real (kind=kind_phys), intent(inout) tauss, real (kind=kind_phys), intent(inout) grain, real (kind=kind_phys), intent(inout) gdd, integer, intent(inout) pgs, real (kind=kind_phys), intent(inout) smcwtd, real (kind=kind_phys), intent(inout) deeprech, real (kind=kind_phys), intent(inout) rech, real (kind=kind_phys), intent(inout) ustarx, real (kind=kind_phys), intent(out) z0wrf, real (kind=kind_phys), intent(out) z0hwrf, real (kind=kind_phys), intent(out) ts, real (kind=kind_phys), intent(out) fsa, real (kind=kind_phys), intent(out) fsr, real (kind=kind_phys), intent(out) fira, real (kind=kind_phys), intent(out) fsh, real (kind=kind_phys), intent(out) ssoil, real (kind=kind_phys), intent(out) fcev, real (kind=kind_phys), intent(out) fgev, real (kind=kind_phys), intent(out) fctr, real (kind=kind_phys), intent(out) ecan, real (kind=kind_phys), intent(out) etran, real (kind=kind_phys), intent(out) edir, real (kind=kind_phys), intent(out) trad, real (kind=kind_phys), intent(out) tgb, real (kind=kind_phys), intent(out) tgv, real (kind=kind_phys), intent(out) t2mv, real (kind=kind_phys), intent(out) t2mb, real (kind=kind_phys), intent(out) q2v, real (kind=kind_phys), intent(out) q2b, real (kind=kind_phys), intent(out) runsrf, real (kind=kind_phys), intent(out) runsub, real (kind=kind_phys), intent(out) apar, real (kind=kind_phys), intent(out) psn, real (kind=kind_phys), intent(out) sav, real (kind=kind_phys), intent(out) sag, real (kind=kind_phys), intent(out) fsno, real (kind=kind_phys), intent(out) nee, real (kind=kind_phys), intent(out) gpp, real (kind=kind_phys), intent(out) npp, real (kind=kind_phys), intent(out) fveg, real (kind=kind_phys), intent(out) albedo, real (kind=kind_phys), intent(out) qsnbot, real (kind=kind_phys), intent(out) ponding, real (kind=kind_phys), intent(out) ponding1, real (kind=kind_phys), intent(out) ponding2, real (kind=kind_phys), intent(out) rssun, real (kind=kind_phys), intent(out) rssha, real (kind=kind_phys), dimension(1:2), intent(out) albd, real (kind=kind_phys), dimension(1:2), intent(out) albi, real (kind=kind_phys), dimension(1:2), intent(out) albsnd, real (kind=kind_phys), dimension(1:2), intent(out) albsni, real (kind=kind_phys), intent(out) bgap, real (kind=kind_phys), intent(out) wgap, real (kind=kind_phys), intent(out) chv, real (kind=kind_phys), intent(out) chb, real (kind=kind_phys), intent(out) emissi, real (kind=kind_phys), intent(out) shg, real (kind=kind_phys), intent(out) shc, real (kind=kind_phys), intent(out) shb, real (kind=kind_phys), intent(out) evg, real (kind=kind_phys), intent(out) evb, real (kind=kind_phys), intent(out) ghv, real (kind=kind_phys), intent(out) ghb, real (kind=kind_phys), intent(out) irg, real (kind=kind_phys), intent(out) irc, real (kind=kind_phys), intent(out) irb, real (kind=kind_phys), intent(out) tr, real (kind=kind_phys), intent(out) evc, real (kind=kind_phys), intent(out) chleaf, real (kind=kind_phys), intent(out) chuc, real (kind=kind_phys), intent(out) chv2, real (kind=kind_phys), intent(out) chb2, real (kind=kind_phys), intent(out) fpice, real (kind=kind_phys), intent(out) pahv, real (kind=kind_phys), intent(out) pahg, real (kind=kind_phys), intent(out) pahb, real (kind=kind_phys), intent(out) pah, real (kind=kind_phys), intent(out) esnow, real (kind=kind_phys), intent(out) canhs, real (kind=kind_phys), intent(out) laisun, real (kind=kind_phys), intent(out) laisha, real (kind=kind_phys), intent(out) rb, real (kind=kind_phys), intent(out) qsfcveg, real (kind=kind_phys), intent(out) qsfcbare, ifdef, ccpp)
Parameters
[in] ice ice (ice = 1)
[in] ist surface type 1->soil; 2->lake
[in] vegtyp vegetation type
[in] croptype crop type
[in] nsnow maximum no. of snow layers
[in] nsoil no. of soil layers
[in] iloc grid index
[in] jloc grid index
[in] dt time step [sec]
[in] zsoil layer-bottom depth from soil surf (m)
[in] q2 mixing ratio (kg/kg) lowest model layer
[in] sfctmp surface air temperature [k]
[in] uu wind speed in eastward dir (m/s)
[in] vv wind speed in northward dir (m/s)
[in] soldn downward shortwave radiation (w/m2)
[in] lwdn downward longwave radiation (w/m2)
[in] sfcprs pressure (pa)
[in] prslkix in exner function
[in] prsik1x in exner function
[in] prslk1x in exner function
[in] garea1 in exner function
[in] pblhx pbl height
[in] iz0tlnd z0t option
[in,out] zlvl reference height (m)
[in] cosz cosine solar zenith angle [0-1]
[in] tbot bottom condition for soil temp. [k]
[in] foln foliage nitrogen (%) [1-saturated]
[in] shdfac green vegetation fraction [0.0-1.0]
[in] yearlen number of days in the particular year.
[in] julian julian day of year (floating point)
[in] lat latitude (radians)
[in] ficeold ice fraction at last timestep
[in] smceq equilibrium soil water content [m3/m3]
[in] prcpconv convective precipitation entering [mm/s] ! mb/an : v3.7
[in] prcpnonc non-convective precipitation entering [mm/s] ! mb/an : v3.7
[in] prcpshcv shallow convective precip entering [mm/s] ! mb/an : v3.7
[in] prcpsnow snow entering land model [mm/s] ! mb/an : v3.7
[in] prcpgrpl graupel entering land model [mm/s] ! mb/an : v3.7
[in] prcphail hail entering land model [mm/s] ! mb/an : v3.7
[in] qc cloud water mixing ratio
[in,out] qsfc mixing ratio at lowest model layer
[in] psfc pressure at lowest model layer
[in] dz8w thickness of lowest layer
[in] shdmax yearly max vegetation fraction
[in,out] qsnow snowfall [mm/s]
[in,out] qrain rainfall [mm/s]
[in,out] fwet wetted or snowed fraction of canopy (-)
[in,out] sneqvo snow mass at last time step (mm)
[in,out] eah canopy air vapor pressure (pa)
[in,out] tah canopy air tmeperature (k)
[in,out] albold snow albedo at last time step (class type)
[in,out] cm momentum drag coefficient
[in,out] ch sensible heat exchange coefficient
[in,out] tauss non-dimensional snow age
[in,out] ustarx friction velocity
[in,out] isnow actual no. of snow layers [-]
[in,out] canliq intercepted liquid water (mm)
[in,out] canice intercepted ice mass (mm)
[in,out] sneqv snow water eqv. [mm]
[in,out] smc soil moisture (ice + liq.) [m3/m3]
[in,out] zsnso layer-bottom depth from snow surf [m]
[in,out] snowh snow height [m]
[in,out] snice snow layer ice [mm]
[in,out] snliq snow layer liquid water [mm]
[in,out] tv vegetation temperature (k)
[in,out] tg ground temperature (k)
[in,out] stc snow/soil temperature [k]
[in,out] sh2o liquid soil moisture [m3/m3]
[in,out] zwt depth to water table [m]
[in,out] wa water storage in aquifer [mm]
[in,out] wt water in aquifer&saturated soil [mm]
[in,out] wslake lake water storage (can be neg.) (mm)
[in,out] smcwtd soil water content between bottom of the soil and water table [m3/m3]
[in,out] deeprech recharge to or from the water table when deep [m]
[in,out] rech recharge to or from the water table when shallow [m] (diagnostic)
[out] z0wrf combined z0 sent to coupled model
[out] z0hwrf combined z0h sent to coupled model
[out] fsa total absorbed solar radiation (w/m2)
[out] fsr total reflected solar radiation (w/m2)
[out] fira total net lw rad (w/m2) [+ to atm]
[out] fsh total sensible heat (w/m2) [+ to atm]
[out] fcev canopy evap heat (w/m2) [+ to atm]
[out] fgev ground evap heat (w/m2) [+ to atm]
[out] fctr transpiration heat (w/m2) [+ to atm]
[out] ssoil ground heat flux (w/m2) [+ to soil]
[out] trad surface radiative temperature (k)
[out] ts surface combined aero temperature (k)
[out] ecan evaporation of intercepted water (mm/s)
[out] etran transpiration rate (mm/s)
[out] edir soil surface evaporation rate (mm/s]
[out] runsrf surface runoff [mm/s]
[out] runsub baseflow (saturation excess) [mm/s]
[out] psn total photosynthesis (umol co2/m2/s) [+]
[out] apar photosyn active energy by canopy (w/m2)
[out] sav solar rad absorbed by veg. (w/m2)
[out] sag solar rad absorbed by ground (w/m2)
[out] fsno snow cover fraction on the ground (-)
[out] fveg green vegetation fraction [0.0-1.0]
[out] albedo surface albedo [-]
[out] qsnbot snowmelt out bottom of pack [mm/s]
[out] ponding surface ponding [mm]
[out] ponding1 surface ponding [mm]
[out] ponding2 surface ponding [mm]
[out] rb leaf boundary layer resistance (s/m)
[out] laisun sunlit leaf area index (m2/m2)
[out] laisha shaded leaf area index (m2/m2)
[out] qsfcveg effective spec humid over vegetation
[out] qsfcbare effective spec humid over bare soil
[out] t2mv 2-m air temperature over vegetated part [k]
[out] t2mb 2-m air temperature over bare ground part [k]
[out] rssun sunlit leaf stomatal resistance (s/m)
[out] rssha shaded leaf stomatal resistance (s/m)
[out] albd albedo (direct)
[out] albi albedo (diffuse)
[out] albsnd snow albedo (direct)
[out] albsni snow albedo (diffuse)
[out] irc canopy net lw rad. [w/m2] [+ to atm]
[out] irg ground net lw rad. [w/m2] [+ to atm]
[out] shc canopy sen. heat [w/m2] [+ to atm]
[out] shg ground sen. heat [w/m2] [+ to atm]
[out] evg ground evap. heat [w/m2] [+ to atm]
[out] ghv ground heat flux [w/m2] [+ to soil]
[out] irb net longwave rad. [w/m2] [+ to atm]
[out] shb sensible heat [w/m2] [+ to atm]
[out] evb evaporation heat [w/m2] [+ to atm]
[out] ghb ground heat flux [w/m2] [+ to soil]
[out] evc canopy evap. heat [w/m2] [+ to atm]
[out] tr transpiration heat [w/m2] [+ to atm]
[out] fpice snow fraction in precipitation
[out] pahv precipitation advected heat - vegetation net (w/m2)
[out] pahg precipitation advected heat - under canopy net (w/m2)
[out] pahb precipitation advected heat - bare ground net (w/m2)
[out] pah precipitation advected heat - total (w/m2)
[out] chv sensible heat exchange coefficient over vegetated fraction
[out] chb sensible heat exchange coefficient over bare-ground
[out] chleaf leaf exchange coefficient
[out] chuc under canopy exchange coefficient
[out] chv2 sensible heat exchange coefficient over vegetated fraction
[out] chb2 sensible heat exchange coefficient over bare-ground
[in] co2air atmospheric co2 concentration (pa)
[in] o2air atmospheric o2 concentration (pa)
[in,out] lfmass leaf mass [g/m2]
[in,out] rtmass mass of fine roots [g/m2]
[in,out] stmass stem mass [g/m2]
[in,out] wood mass of wood (incl. woody roots) [g/m2]
[in,out] stblcp stable carbon in deep soil [g/m2]
[in,out] fastcp short-lived carbon, shallow soil [g/m2]
[in,out] lai leaf area index [-]
[in,out] sai stem area index [-]
[in,out] grain grain mass [g/m2]
[in,out] gdd growing degree days
[in,out] pgs plant growing stage [-]
[out] nee net ecosys exchange (g/m2/s co2)
[out] gpp net instantaneous assimilation [g/m2/s c]
[out] npp net primary productivity [g/m2/s c]
Definition at line 421 of file module_sf_noahmplsm.F90.
References albedo(), atm(), carbon(), carbon_crop(), energy(), error(), phenology(), precip_heat(), and water().
Referenced by noahmpdrv_run().